services:
  rabbitmq:
    image: rabbitmq:4.3.1-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=thinkvitals
      - RABBITMQ_DEFAULT_PASS=J5RnL6Wofj8IEDXEkJ4p
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

networks:
  default:

volumes:
  rabbitmq_logs:
    driver: local
  rabbitmq_data:
    driver: local
